on:
  push:
    branches:
      new-code
  pull_request:

permissions: write-all
jobs:
  test-auto-approve:
    name: test-auto-approve
    runs-on: ubuntu-latest
    steps:
      - name: filler
        run: echo "this is a filler"
      
      - name: create PR
        run: | 
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/coriky/actions/pulls" \
            -d '{"title": "new PR from GHA", "body": "PRR BODY", "head": "new-code", "base": "main"}'
            
            
      - name: approve PR
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/coriky/actions/pulls/${{ github.event.number }}/reviews" \
            -d '{"event": "APPROVE"}'
        
      - name: merge pR
        run: |
          curl \
            -X PUT \
            -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/coriky/actions/pulls/${{ github.event.number }}/merge" 
            
          
            
      
      
